- name: Deploy epress application
  hosts: all
  become: yes
  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present

    - name: Clone the latest epress code
      git:
        repo: "git@github.com:epressworld/epress.git"
        dest: /opt/epress
        version: HEAD
        force: yes

    - name: Change to code directory
      shell: cd /opt/epress && docker build -t epressworld/epress .
      args:
        chdir: /opt/epress

    - name: Remove old epress container if exists
      shell: docker rm -f epress
      ignore_errors: yes

    - name: Run new epress container
      shell: docker run --name epress -d --rm --network epress -v /srv/epress/data:/srv/data -v /srv/epress/client.env:/srv/client/.env.local -v /srv/epress/server.env:/srv/.env -p 3000:3000 -p 3001:3001 epressworld/epress

    - name: Image prune
      shell: docker system prune -af