name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push-release-docker:
    name: Build and Push Release Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest # Add latest tag for releases

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-and-push-release-docker
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }} # Solution 1: Checkout default branch
          fetch-depth: 0 # Fetch all history

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: ${{ github.event.repository.default_branch }}
          skip-bump: true  # 关键：跳过自动 bump，只生成 changelog
          skip-commit: true  # 跳过 commit（我们手动做了）
          skip-tag: true  # 跳过 tag（release 步骤处理）
          skip-on-empty: true  # 无新 commits 时跳过

      - name: Create Release
        uses: softprops/action-gh-release@v2 # Solution 3: Use softprops/action-gh-release
        with:
          tag_name: ${{ github.ref_name }}  # 修复：用 ref_name，如 0.1.1
          name: ${{ github.ref_name }}  # 修复：release 标题
          body: ${{ steps.changelog.outputs.changelog }}  # tag 间 changelog
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}